Initialized employee subclasses in EmployeeManager
CSC207-UofT/course-project-javacado-s pull request #92
Opened 2021-12-05 00:25 UTC by FaithD186

added employee subclasses to employee_list

2021-12-05 17:09 UTC, yi1z approved these changes

2021-12-05 17:14 UTC, yi1z commented
I resolved the conflicts, but I still need Faith to check if the implementations are still correct and can do the job

2021-12-05 20:03 UTC, Maggie39 approved these changes

2021-12-06 04:51 UTC, h4kureii requested changes
Uhhhhh this edition of EmployeeManager is outdated. We don't use addEmployee() anymore, and employees.txt isn't created when it's not found anymore (we just assume it exists now).
We're also moving the text parsing into EmployeeManagerReadWriter, so I think we should hold off on this PR until we merge EmployeeManagerReadWriter, then fix it after.

Friendly reminder to all to regularly update your branches.

2021-12-06 15:47 UTC, FaithD186 commented
> Uhhhhh this edition of EmployeeManager is outdated. We don't use addEmployee() anymore, and employees.txt isn't created when it's not found anymore (we just assume it exists now). We're also moving the text parsing into EmployeeManagerReadWriter, so I think we should hold off on this PR until we merge EmployeeManagerReadWriter, then fix it after.
Ok, I'll fix this after we merge EmployeeManagerReadWriter

2021-12-06 17:48 UTC, closed without merging